config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :corps
  resources :companies
  resources :contracts
  get 'contact/index'
  resources :comments
  resources :types
  resources :categories
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/aboutus',    to: 'static_pages#aboutus'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get 'contact',  to: 'contact#index'
  post 'contact/confirm',  to: 'contact#confirm'
  post 'contact/thanks',  to: 'contact#thanks'
  get   '/typeahead' => 'items#typeahead_action'
  get   '/create_contract',   to: 'contracts#make_new'
  post   '/update_contract',   to: 'contracts#change_data'
  post   '/get_contract',   to: 'contracts#get_contract'
  post   '/create_event',   to: 'events#make_new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :items
  resources :updates
  resources :reviews
  resources :relationships,       only: [:create, :destroy]

end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry
  has_many :items  
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user  
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX ,:message => 'メールアドレスを入力してください'}
end

app/models/contract.rb
class Contract < ApplicationRecord
end

app/models/corp.rb
class Corp < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :reviews
  belongs_to :type
  belongs_to :category
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"  
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    default_scope -> { order(created_at: :desc) }
    mount_uploader :picture, PictureUploader
    validates :user_id, presence: true
    validates :content, presence: true
    belongs_to :item
    validates :item_id,  presence: true
    validate  :picture_size
    validates :title, presence: true
    validates :point, presence: true, numericality:{less_than_or_equal_to: 5,greter_than_or_equal_to: 1}
#    validates :point,  presence: true, inclusion: { in: %w(1,2,3,4,5), message: "1から5で評価してください" }
    has_many  :comments

private
  # アップロードされた画像のサイズをバリデーションする
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, "5MB以下の画像にしてください")
    end
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :items
end

app/models/update.rb
class Update < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :active_relationships, class_name:  "Relationship",
                                foreign_key: "follower_id",
                                dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many  :comments

  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
  SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
  update_attribute(:remember_digest, nil)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
   Review.where("user_id IN (#{following_ids})
                    OR user_id = :user_id", user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/static_pages_controller.rb
require 'ethereum'

class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @user = User.find(session[:user_id])
    end
    if  defined?($address)
      contract = Ethereum::Contract.create(file: "test.sol", address: $address, client: $client)
      @get = contract.call.get();
      @get_sender = contract.call.get_sender();
      @get_receiver = contract.call.get_receiver();
      @get_status = contract.call.get_status();
      @get_created_at = contract.call.get_created_at();
      @get_updated_at = contract.call.get_updated_at();
    else
      @get = "none"
    end
  end

  def help
  end

  def aboutus
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/corps_helper.rb
module CorpsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/items_helper.rb
module ItemsHelper

def latest_item
@item = Item.first(3)
end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
    def latest_review
    @reviews = Review.first(3)
    end
end

app/helpers/static_pages_helper.rb
require 'ethereum'

module StaticPagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/aboutus.erb
<div class="center jumbotron title">
  <h1>「楽しい」を共有しよう　Revie</h1>
  <p>書評・レビューを書いて、あなたの感想を共有しよう。もしかしたら、その評価がお金になるかもしれません。小説・漫画・映画・ゲームなんでもOK</p>
</div>
<% breadcrumb :aboutus %>
  <h2>最新の更新</h2>
  <div class="row row-eq-height">
    <div class="panel panel-default col-md-6">
      <% latest_update.each do |update|%>
        <%= link_to update do%>
          <div class="panel panel-primary"><%= update[:created_at] %>更新</div>
          <div class="panel-body"><p class="update"><%= update[:title] %></p></div>
        <% end %>
    <% end %>
  </div>

<div class="col-md-6">
</div>
<div class="col-md-6">
</div>

    <div class="col-md-6">
      <h2>感想を表現したい。でも、SNSで目立ちたくない。</h2>
      <p>本を読んだ時、映画を見た時、ゲームをクリアした時、どんな時でもいいけれど、
        ふと「この感動を誰かに伝えたいとおもったことはありませんか？
        そんな時、SNSではなんだか格好をつけてるみたいだし、すぐに埋もれて消えてしまう。
        そんな思いを持った方に、ぜひこのサイトで気軽に「楽しい」を共有していただきたいです。</p>
    </div>

    <div class="col-md-6">
    </div>
    <div class="col-md-6">
    </div>

    <div class="col-md-6">
      <h2>もしかしたら、人を感動させる評論になるかもしれない。</h2>
      <p>あなたの書いた評論は、本当に匿名掲示板やSNSで消費されるコンテンツなのでしょうか？
        もともと、評論とは1つの文学的活動であり、十分に世に出す価値のあるものです。
        インターネットの発達によって消費されるようになった評論ですが、あなたの評論は少し違うかもしれません。
        ひょっとすると誰かを感動させるかもしれない。そんな可能性を確かめて見ませんか？</p>
    </div>

    <div class="col-md-6">
    </div>
    <div class="col-md-6">
    </div>

<aside class="col-md-6">
<h2>レビューを書いて見ませんか</h2>
    <% if logged_in? %>
          <section class="user_info">
            <%= render 'shared/user_info' %>
          </section>
          <section class="stats">
            <%= render 'shared/stats' %>
          </section>
          <section class="review_form">
            <%= render 'shared/review_form' %>
          </section>
      <% else %>
        <%= render 'shared/review_form' %>
        <div class="text-right">
          <span>会員なら本棚作成や報酬受取が可能です</span>
          <li class="btn btn-primary"><%= link_to "会員登録 ＞", signup_path %></li>
        </div>
    <% end %>
</aside>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "ヘルプ") %>
<div class="page-header">
  <h1>ヘルプ</h1>
</div>
<% breadcrumb :help %>
  <h2>
    何をするサイトなのか
  </h2>
  <p class="site_description">
    Revieでは読んだ本や観た映画の感想を、誰にアピールするでもなく発信してもらう場です。<br>
    名前の出ているSNSでは恥ずかしい評論でも、口汚い罵りでも、なんでも発信してもらうことを目的にしています。<br>
    さらに、そのレビューによって誰かが新しく本やブルーレイを購入すれば、広告費を還元いたします。
  </p>

  <h2>
    どうやって広告費を還元するか
  </h2>
  <p class="site_description">
    アフィリエイトで得た広告収入を、レビュアーに還元します。
    本当はもっと多く収益を還元したいのですが、鋭意努力しますので、お待ちください。
    成果が出た月に、ご登録いただいたメールアドレスにご連絡して、送金手続きを行います。
  </p>


  <h2>
    よくある質問 / FAQ
  </h2>
    <ul id="faq">
      <li>有料ですか？
        <p>全部無料で運営しています。気にされずに利用してください。</p>
      </li>
      <li>会員登録は必須ですか？
      <p>不要です。ただし、本棚機能やフォロー機能、キャッシュバックといった機能が会員限定になっております。</p>
    </li>
      <li>運営元はどこですか？
      <p>個人で運営しています。ご連絡が必要な場合は、問い合わせフォームにお願いします。</p>
    </li>
    </ul>

app/views/static_pages/home.html.erb
<script>
function link_to(link) {
  location.href = link;
}
</script>

<h1>絶対に信頼できる履歴書を</h1>
<h2>ブロックチェーンで働きぶりまで追跡</h2>
<div class="row">
  <aside class="col-md-6">
<h4>何をやるのか</h4>
<p>ブロックチェーンを用いて社内の評価を全て保存。働きぶりと職場・賞罰を全て管理します。</p>
<h4>なぜやるのか</h4>
<p>今は人手不足だと言われていますが、転職できずにブラック企業に苦しむ人もいます。転職をもっと確実なものにすることで、本当に頑張りたい人がリスクを取らなくて良い社会を実現したいです。</p>
  </aside>
</div>

<div class="row">
  <aside class="col-md-6">
<% if logged_in? %>
<div class=button>
  <%= link_to "マイページへ", current_user,class: "btn btn-primary" %>
</div>
</aside>
</div>


  <%= link_to "ログアウト", logout_path, method: :delete,class: "btn" %>

<% else %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me, class: "checkbox inline" do %>
        <%= f.check_box :remember_me %>
        <span>次回から自動的にログイン</span>
      <% end %>

      <%= f.submit "ログイン", class: "btn btn-primary" %>
    <% end %>

    <p>まだの方は <%= link_to "会員登録へ", signup_path %></p>
  </div>
</div>
<% end %>